/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DragCom: typeof import('./src/components/DragCom/DragCom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    LogCom: typeof import('./src/components/log/logCom.vue')['default']
    OptionsCom: typeof import('./src/components/options/optionsCom.vue')['default']
    QuestionCheckbox: typeof import('./src/components/QuestionComponents/QuestionCheckBox/QuestionCheckbox.vue')['default']
    QuestionCheckboxPropsCom: typeof import('./src/components/QuestionComponents/QuestionCheckBox/QuestionCheckboxPropsCom.vue')['default']
    QuestionInfo: typeof import('./src/components/QuestionComponents/QuestionInfo/QuestionInfo.vue')['default']
    QuestionInfoPropsCom: typeof import('./src/components/QuestionComponents/QuestionInfo/QuestionInfoPropsCom.vue')['default']
    QuestionInput: typeof import('./src/components/QuestionComponents/QuestionInput/QuestionInput.vue')['default']
    QuestionParagraph: typeof import('./src/components/QuestionComponents/QuestionParagraph/QuestionParagraph.vue')['default']
    QuestionParagraphPropsCom: typeof import('./src/components/QuestionComponents/QuestionParagraph/QuestionParagraphPropsCom.vue')['default']
    QuestionRadio: typeof import('./src/components/QuestionComponents/QuestionRadio/QuestionRadio.vue')['default']
    QuestionRadioPropsCom: typeof import('./src/components/QuestionComponents/QuestionRadio/QuestionRadioPropsCom.vue')['default']
    QuestionTextarea: typeof import('./src/components/QuestionComponents/QuestionTextarea/QuestionTextarea.vue')['default']
    QuestionTextareaPropsCom: typeof import('./src/components/QuestionComponents/QuestionTextarea/QuestionTextareaPropsCom.vue')['default']
    QuestionTitle: typeof import('./src/components/QuestionComponents/QuestionTitle/QuestionTitle.vue')['default']
    QuestionTitlePropsCom: typeof import('./src/components/QuestionComponents/QuestionTitle/QuestionTitlePropsCom.vue')['default']
    QuestionUpload: typeof import('./src/components/QuestionComponents/QuestionUpload/QuestionUpload.vue')['default']
    QuestionUploadPropsCom: typeof import('./src/components/QuestionComponents/QuestionUpload/QuestionUploadPropsCom.vue')['default']
    QuetionsInputPropsCom: typeof import('./src/components/QuestionComponents/QuestionInput/QuetionsInputPropsCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./src/components/QuestionComponents/QuestionUpload/UploadFile.vue')['default']
  }
}
