import { createApp } from "vue";
import App from "./App.vue";
import ElementPlus from "element-plus";
import zhCn from "element-plus/es/locale/lang/zh-cn";
import pinia from "./store";
import "element-plus/dist/index.css";
import "./style/resetCss.css";
import "./style/font.css";
import "./style/var.css";
import router from "./router";
const app = createApp(App);
app.use(pinia);
app.use(router);
app.use(ElementPlus, { locale: zhCn });
app.mount("#app");
document.documentElement.classList.add("light");
